[[repos]]
name = "tmux"
url = "git@github.com:moecly/tmux-config.git"

[[repos.links]]
source = ".tmux.conf"
target = "~/.tmux.conf"
scope = "user"

[[repos.links]]
source = ".tmux.conf.local"
target = "~/.tmux.conf.local"
scope = "user"

[[repos]]
name = "zsh"
url = "git@github.com:moecly/zsh-config.git"

[[repos.links]]
source = ".zshrc"
target = "~/.zshrc"
scope = "user"

[[repos]]
name = "nvim"
url = "git@github.com:moecly/nvim-config.git"

[[repos.links]]
source = "."
target = "~/.config/nvim"
scope = "user"

[[repos]]
name = "alacritty"
url = "git@github.com:moecly/alacritty-config.git"

[[repos.links]]
source = "."
target = "~/.config/alacritty"
scope = "user"

[[repos]]
name = "keyd"
url = "git@github.com:moecly/keyd-config.git"

[[repos.links]]
source = "."
target = "/etc/keyd"
scope = "system"

[[repos]]
name = "niri"
url = "git@github.com:moecly/niri-config.git"

[[repos.links]]
source = "."
target = "~/.config/niri"
scope = "user"

[[repos]]
name = "kitty"
url = "git@github.com:moecly/kitty-config.git"

[[repos.links]]
source = "."
target = "~/.config/kitty"
scope = "user"

[[repos]]
name = "swaylock"
url = "git@github.com:moecly/swaylock-config.git"

[[repos.links]]
source = "."
target = "~/.config/swaylock"
scope = "user"

[[repos]]
name = "fuzzel"
url = "git@github.com:moecly/fuzzel-config.git"

[[repos.links]]
source = "."
target = "~/.config/fuzzel"
scope = "user"

[[repos]]
name = "fontconfig"
url = "git@github.com:moecly/fontconfig-config.git"

[[repos.links]]
source = "."
target = "~/.config/fontconfig"
scope = "user"

[[repos]]
name = "wlogout"
url = "git@github.com:moecly/wlogout-config.git"

[[repos.links]]
source = "."
target = "~/.config/wlogout"
scope = "user"

[[repos]]
name = "DankMaterialShell"
url = "git@github.com:moecly/dms-shell-config.git"

[[repos.links]]
source = "."
target = "~/.config/DankMaterialShell"
scope = "user"
